services:
  - type: worker
    name: discord-bot-expense-tracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python discord-bot-expense-tracker.py"
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON_CONTENT
        sync: false
